"""Versioned factual reference data for W01 4B. Not a calibrated equation of state.

Sources are cited at property level. Only numerical facts and original Atlas
metadata are included, not redistributed papers. Ranges retain their actual
meaning: independent literature ranges are not statistical confidence intervals.
Selecting a midpoint is an explicit Atlas modelling choice. Different specimens
and measurement conditions must not be mistaken for one perfectly known rock.

This is Python source so the existing source inventory and execution-context
checks include the data bytes, without a second unverified package-data loader.
"""
LIBRARY_VERSION = "earth-reference-2026-09-17.v1"

SOURCES = (('KAKOKO2023',
  'Kakoko, Jande et al. (2023), ACS Omega 8, 18554–18565; doi:10.1021/acsomega.3c00314',
  'https://pubs.acs.org/doi/10.1021/acsomega.3c00314',
  'Table 3, literature compilation at 20 °C. Factual values only; no article text or illustrations '
  'distributed. Natural ranges are not confidence intervals or a matched specimen.'),
 ('GOTO2008',
  'Goto and Matsubayashi (2008), JGR; doi:10.1029/2007JB005119',
  'https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2007JB005119',
  'Table 3, room-condition constituent values, with upstream references and calculated entries. 293.15 K is '
  'the library nominal room reference, not a claim of identical experimental temperatures.'),
 ('LEE2015',
  'Lee, Park, Park and Park (2015), Tunnel and Underground Space 25(1), 1–23; doi:10.7474/TUS.2015.25.1.001',
  'https://www.researchgate.net/publication/277645110_Current_Status_of_Research_on_Thermal_and_Mechanical_Properties_of_Rock_under_High-Temperature_Condition',
  'Author-posted full report. Tables 1/2/5/6/7/8. Table 8 credits Waples and Waples (2004); table 5 credits '
  'Skinner/Robie/Robertson. Table 1 heat capacities mostly at 0 °C; table 5 expansion is a 20–400 °C secant, '
  'NOT instantaneous room-temperature expansion. Ambiguous and anomalous rows are excluded.'),
 ('ANDUJAR2016',
  'Andújar Márquez, Martínez Bohórquez and Gómez Melgar (2016), Sensors 16, 306; doi:10.3390/s16030306',
  'https://www.mdpi.com/1424-8220/16/3/306',
  'Table 1 thermal conductivity reference values. Rock-class typical values, not calibrated '
  'mantle-temperature laws. Actual pore state and exact measurement conditions are not resolved by this '
  'compilation.'),
 ('WATER2024',
  'Vukelić and Šporin (2024), Groundwater Potential for the Utilisation of Shallow Geothermal Energy from a '
  'Closed Coal Mine, Water 16, 1572; doi:10.3390/w16111572',
  'https://www.mdpi.com/2073-4441/16/11/1572',
  'Table 6 ranges used only for shale and gypsum conductivity, and stated ice reference. Excludes '
  'inconsistent air density and reversed sand heat-capacity range in this table.'),
 ('WATER2019',
  'Evaluation of Heat Transfer Performance of a Multi-Disc Sorption Bed (2019), Energies 12, 4660; '
  'doi:10.3390/en12244660',
  'https://www.mdpi.com/1996-1073/12/24/4660',
  'Table 2 liquid-water model inputs. 20 °C is an explicit nominal reference for this rounded engineering '
  'set, not a full IAPWS equation of state.'),
 ('HUOTARI2004',
  'Huotari and Kukkonen (2004), Posiva Working Report 2004-04, Geological Survey of Finland',
  'https://studylib.net/doc/8402570/thermal-expansion-properties-of-rocks',
  'Full report mirror, Table 3, Dane (1942) population values over 20–100 °C. Linear coefficients converted '
  'to volumetric by 3 only under the explicitly assumed isotropic reference. Not a tensor or a '
  'temperature-dependent law.'),
 ('HASTEROK2018',
  'Hasterok, Gard and Webb (2018), Geoscience Frontiers 9, 1777–1794; doi:10.1016/j.gsf.2017.10.012',
  'https://www.researchgate.net/publication/321043977_On_the_radiogenic_heat_production_of_metamorphic_igneous_and_sedimentary_rocks',
  'Author-posted preprint, section 5.3: aluminous shale 2.9 and iron-rich shale 1.7 microW/m3. Population '
  'representatives, not universal source rates or cooling ages.'),
 ('RYBACH2023',
  'Application of in-situ gamma spectrometry (2023), Geothermal Energy; doi:10.1186/s40517-023-00273-3',
  'https://link.springer.com/article/10.1186/s40517-023-00273-3',
  'Equation 2 reproduces the Rybach model: microW/m3 = rho[kg/m3]*1e-5*(9.52 U[ppm]+2.56 Th[ppm]+3.48 '
  'K[wt%]). The published prose omits the coefficient scalings; this library follows the dimensioned '
  'equation. Natural present-day isotope mixture, not radioactive evolution.'),
 ('BANKS2025',
  'Banks (2025), porosity and saturation effects; doi:10.47248/ges2505030007',
  'https://eprints.gla.ac.uk/365772/',
  'Bulk volumetric heat capacity is volume-weighted. Conductivity depends on geometry/saturation; geometric '
  'mixing is not universally valid for dry porous material. Conductivity bounds and explicit structure '
  'selection are retained.'),
 ('BURNMAN',
  'BurnMan composite and averaging-scheme documentation',
  'https://burnman.readthedocs.io/en/latest/materials_05_composite.html',
  'Distinguishes mass, mole and volume fractions and properties evaluated at a thermodynamic state. Method '
  'reference only; no BurnMan code/database is bundled.'))

# Immutable raw tuples; see material_library.PropertyDatum for field definitions.
ROWS = (('rock.granite',
  'Granite',
  'igneous_felsic',
  'bulk_reference',
  (),
  (('density',
    2.65,
    'g/cm3',
    'KAKOKO2023',
    'Table 3: granite density',
    (2.6, 2.7),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('heat_capacity',
    0.775,
    'J/g/K',
    'KAKOKO2023',
    'Table 3: granite specific heat',
    (0.6, 0.95),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('conductivity',
    2.85,
    'W/m/K',
    'KAKOKO2023',
    'Table 3: granite conductivity',
    (2.6, 3.1),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('thermal_expansion',
    8.0,
    'linear_micro/K_isotropic',
    'HUOTARI2004',
    'Table 3: Dane 1942 granite family',
    (5.0, 11.0),
    'isotropic_interval_secant',
    293.15,
    (293.15, 373.15),
    '3×linear as isotropic small-strain approximation over 20–100 C; not a crystalline tensor or instantaneous '
    'derivative.')),
  'Independent compiled ranges; midpoint is an Atlas representative selection, not a measured mean or joint '
  'sample. Porosity/saturation are unresolved; do not add pore space to this bulk reference.'),
 ('rock.granodiorite',
  'Granodiorite',
  'igneous_felsic',
  'bulk_reference',
  (),
  (('density', 2.7, 'g/cm3', 'KAKOKO2023', 'Table 3: granodiorite density', None, 'reported', 293.15, None, ''),
   ('heat_capacity',
    0.835,
    'J/g/K',
    'KAKOKO2023',
    'Table 3: granodiorite specific heat',
    (0.65, 1.02),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('conductivity',
    2.35,
    'W/m/K',
    'KAKOKO2023',
    'Table 3: granodiorite conductivity',
    (2.1, 2.6),
    'midpoint_of_reported_range',
    293.15,
    None,
    '')),
  'Independent compiled ranges; midpoint is an Atlas representative selection, not a measured mean or joint '
  'sample. Porosity/saturation are unresolved; do not add pore space to this bulk reference.'),
 ('rock.rhyolite',
  'Rhyolite',
  'igneous_felsic',
  'bulk_reference',
  (),
  (('density',
    2.45,
    'g/cm3',
    'KAKOKO2023',
    'Table 3: rhyolite density',
    (2.3, 2.6),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('heat_capacity',
    0.785,
    'J/g/K',
    'KAKOKO2023',
    'Table 3: rhyolite specific heat',
    None,
    'reported',
    293.15,
    None,
    ''),
   ('conductivity',
    1.95,
    'W/m/K',
    'KAKOKO2023',
    'Table 3: rhyolite conductivity',
    (1.6, 2.3),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('thermal_expansion',
    8.0,
    'linear_micro/K_isotropic',
    'HUOTARI2004',
    'Table 3: Dane 1942 rhyolite family',
    (5.0, 11.0),
    'isotropic_interval_secant',
    293.15,
    (293.15, 373.15),
    '3×linear as isotropic small-strain approximation over 20–100 C; not a crystalline tensor or instantaneous '
    'derivative.')),
  'Independent compiled ranges; midpoint is an Atlas representative selection, not a measured mean or joint '
  'sample. Porosity/saturation are unresolved; do not add pore space to this bulk reference.'),
 ('rock.diorite',
  'Diorite',
  'igneous_intermediate',
  'bulk_reference',
  (),
  (('density',
    2.9,
    'g/cm3',
    'KAKOKO2023',
    'Table 3: diorite density',
    (2.8, 3.0),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('heat_capacity',
    1.0,
    'J/g/K',
    'KAKOKO2023',
    'Table 3: diorite specific heat',
    None,
    'reported',
    293.15,
    None,
    ''),
   ('conductivity',
    2.5,
    'W/m/K',
    'KAKOKO2023',
    'Table 3: diorite conductivity',
    None,
    'reported',
    293.15,
    None,
    ''),
   ('thermal_expansion',
    7.0,
    'linear_micro/K_isotropic',
    'HUOTARI2004',
    'Table 3: Dane 1942 diorite family',
    (5.0, 9.0),
    'isotropic_interval_secant',
    293.15,
    (293.15, 373.15),
    '3×linear as isotropic small-strain approximation over 20–100 C; not a crystalline tensor or instantaneous '
    'derivative.')),
  'Independent compiled ranges; midpoint is an Atlas representative selection, not a measured mean or joint '
  'sample. Porosity/saturation are unresolved; do not add pore space to this bulk reference.'),
 ('rock.andesite',
  'Andesite',
  'igneous_intermediate',
  'bulk_reference',
  (),
  (('density',
    2.65,
    'g/cm3',
    'KAKOKO2023',
    'Table 3: andesite density',
    (2.6, 2.7),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('heat_capacity',
    0.815,
    'J/g/K',
    'KAKOKO2023',
    'Table 3: andesite specific heat',
    None,
    'reported',
    293.15,
    None,
    ''),
   ('conductivity',
    2.55,
    'W/m/K',
    'KAKOKO2023',
    'Table 3: andesite conductivity',
    (2.3, 2.8),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('thermal_expansion',
    7.0,
    'linear_micro/K_isotropic',
    'HUOTARI2004',
    'Table 3: Dane 1942 andesite family',
    (5.0, 9.0),
    'isotropic_interval_secant',
    293.15,
    (293.15, 373.15),
    '3×linear as isotropic small-strain approximation over 20–100 C; not a crystalline tensor or instantaneous '
    'derivative.')),
  'Independent compiled ranges; midpoint is an Atlas representative selection, not a measured mean or joint '
  'sample. Porosity/saturation are unresolved; do not add pore space to this bulk reference.'),
 ('rock.gabbro',
  'Gabbro',
  'igneous_mafic',
  'bulk_reference',
  (),
  (('density',
    2.95,
    'g/cm3',
    'KAKOKO2023',
    'Table 3: gabbro density',
    (2.9, 3.0),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('heat_capacity',
    0.8,
    'J/g/K',
    'KAKOKO2023',
    'Table 3: gabbro specific heat',
    (0.6, 1.0),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('conductivity',
    2.05,
    'W/m/K',
    'KAKOKO2023',
    'Table 3: gabbro conductivity',
    (1.5, 2.6),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('thermal_expansion',
    5.4,
    'linear_micro/K_isotropic',
    'HUOTARI2004',
    'Table 3: Dane 1942 gabbro family',
    (4.4, 6.4),
    'isotropic_interval_secant',
    293.15,
    (293.15, 373.15),
    '3×linear as isotropic small-strain approximation over 20–100 C; not a crystalline tensor or instantaneous '
    'derivative.')),
  'Independent compiled ranges; midpoint is an Atlas representative selection, not a measured mean or joint '
  'sample. Porosity/saturation are unresolved; do not add pore space to this bulk reference.'),
 ('rock.basalt',
  'Basalt',
  'igneous_mafic',
  'bulk_reference',
  (),
  (('density',
    2.65,
    'g/cm3',
    'KAKOKO2023',
    'Table 3: basalt density',
    (2.3, 3.0),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('heat_capacity',
    0.965,
    'J/g/K',
    'KAKOKO2023',
    'Table 3: basalt specific heat',
    (0.7, 1.23),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('conductivity',
    1.75,
    'W/m/K',
    'KAKOKO2023',
    'Table 3: basalt conductivity',
    (1.2, 2.3),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('thermal_expansion',
    5.4,
    'linear_micro/K_isotropic',
    'HUOTARI2004',
    'Table 3: Dane 1942 basalt family',
    (4.4, 6.4),
    'isotropic_interval_secant',
    293.15,
    (293.15, 373.15),
    '3×linear as isotropic small-strain approximation over 20–100 C; not a crystalline tensor or instantaneous '
    'derivative.')),
  'Independent compiled ranges; midpoint is an Atlas representative selection, not a measured mean or joint '
  'sample. Porosity/saturation are unresolved; do not add pore space to this bulk reference.'),
 ('rock.dolerite',
  'Dolerite',
  'igneous_mafic',
  'bulk_reference',
  ('diabase',),
  (('density',
    2.8,
    'g/cm3',
    'KAKOKO2023',
    'Table 3: dolerite density',
    (2.7, 2.9),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('heat_capacity',
    0.885,
    'J/g/K',
    'KAKOKO2023',
    'Table 3: dolerite specific heat',
    (0.87, 0.9),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('conductivity',
    2.6,
    'W/m/K',
    'KAKOKO2023',
    'Table 3: dolerite conductivity',
    (2.2, 3.0),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('thermal_expansion',
    5.4,
    'linear_micro/K_isotropic',
    'HUOTARI2004',
    'Table 3: Dane 1942 dolerite family',
    (4.4, 6.4),
    'isotropic_interval_secant',
    293.15,
    (293.15, 373.15),
    '3×linear as isotropic small-strain approximation over 20–100 C; not a crystalline tensor or instantaneous '
    'derivative.')),
  'Independent compiled ranges; midpoint is an Atlas representative selection, not a measured mean or joint '
  'sample. Porosity/saturation are unresolved; do not add pore space to this bulk reference.'),
 ('rock.sandstone',
  'Sandstone',
  'sedimentary_siliciclastic',
  'bulk_reference',
  (),
  (('density',
    2.4,
    'g/cm3',
    'KAKOKO2023',
    'Table 3: sandstone density',
    (2.2, 2.6),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('heat_capacity',
    0.82,
    'J/g/K',
    'KAKOKO2023',
    'Table 3: sandstone specific heat',
    (0.69, 0.95),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('conductivity',
    2.3,
    'W/m/K',
    'KAKOKO2023',
    'Table 3: sandstone conductivity',
    (1.7, 2.9),
    'midpoint_of_reported_range',
    293.15,
    None,
    '')),
  'Independent compiled ranges; midpoint is an Atlas representative selection, not a measured mean or joint '
  'sample. Porosity/saturation are unresolved; do not add pore space to this bulk reference.'),
 ('rock.quartzitic_sandstone',
  'Quartzitic sandstone',
  'sedimentary_siliciclastic',
  'bulk_reference',
  (),
  (('density',
    2.6,
    'g/cm3',
    'KAKOKO2023',
    'Table 3: quartzitic_sandstone density',
    None,
    'reported',
    293.15,
    None,
    ''),
   ('heat_capacity',
    0.652,
    'J/g/K',
    'KAKOKO2023',
    'Table 3: quartzitic_sandstone specific heat',
    None,
    'reported',
    293.15,
    None,
    ''),
   ('conductivity',
    5.1,
    'W/m/K',
    'KAKOKO2023',
    'Table 3: quartzitic_sandstone conductivity',
    (5.0, 5.2),
    'midpoint_of_reported_range',
    293.15,
    None,
    '')),
  'Independent compiled ranges; midpoint is an Atlas representative selection, not a measured mean or joint '
  'sample. Porosity/saturation are unresolved; do not add pore space to this bulk reference.'),
 ('rock.calcareous_sandstone',
  'Calcareous sandstone',
  'sedimentary_siliciclastic',
  'bulk_reference',
  (),
  (('density',
    2.7,
    'g/cm3',
    'KAKOKO2023',
    'Table 3: calcareous_sandstone density',
    None,
    'reported',
    293.15,
    None,
    ''),
   ('heat_capacity',
    0.652,
    'J/g/K',
    'KAKOKO2023',
    'Table 3: calcareous_sandstone specific heat',
    None,
    'reported',
    293.15,
    None,
    ''),
   ('conductivity',
    4.4,
    'W/m/K',
    'KAKOKO2023',
    'Table 3: calcareous_sandstone conductivity',
    None,
    'reported',
    293.15,
    None,
    '')),
  'Independent compiled ranges; midpoint is an Atlas representative selection, not a measured mean or joint '
  'sample. Porosity/saturation are unresolved; do not add pore space to this bulk reference.'),
 ('rock.limestone',
  'Limestone',
  'sedimentary_carbonate',
  'bulk_reference',
  (),
  (('density',
    2.55,
    'g/cm3',
    'KAKOKO2023',
    'Table 3: limestone density',
    (2.3, 2.8),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('heat_capacity',
    0.795,
    'J/g/K',
    'KAKOKO2023',
    'Table 3: limestone specific heat',
    (0.68, 0.91),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('conductivity',
    2.5,
    'W/m/K',
    'KAKOKO2023',
    'Table 3: limestone conductivity',
    (2.0, 3.0),
    'midpoint_of_reported_range',
    293.15,
    None,
    '')),
  'Independent compiled ranges; midpoint is an Atlas representative selection, not a measured mean or joint '
  'sample. Porosity/saturation are unresolved; do not add pore space to this bulk reference.'),
 ('rock.dolostone',
  'Dolostone',
  'sedimentary_carbonate',
  'bulk_reference',
  (),
  (('density', 2.8, 'g/cm3', 'KAKOKO2023', 'Table 3: dolostone density', None, 'reported', 293.15, None, ''),
   ('heat_capacity',
    0.8,
    'J/g/K',
    'KAKOKO2023',
    'Table 3: dolostone specific heat',
    None,
    'reported',
    293.15,
    None,
    ''),
   ('conductivity',
    2.1,
    'W/m/K',
    'KAKOKO2023',
    'Table 3: dolostone conductivity',
    None,
    'reported',
    293.15,
    None,
    '')),
  'Independent compiled ranges; midpoint is an Atlas representative selection, not a measured mean or joint '
  'sample. Porosity/saturation are unresolved; do not add pore space to this bulk reference.'),
 ('rock.marble',
  'Marble',
  'metamorphic',
  'bulk_reference',
  (),
  (('density',
    2.65,
    'g/cm3',
    'KAKOKO2023',
    'Table 3: marble density',
    (2.6, 2.7),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('heat_capacity',
    0.84,
    'J/g/K',
    'KAKOKO2023',
    'Table 3: marble specific heat',
    (0.8, 0.88),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('conductivity',
    2.75,
    'W/m/K',
    'KAKOKO2023',
    'Table 3: marble conductivity',
    (2.3, 3.2),
    'midpoint_of_reported_range',
    293.15,
    None,
    '')),
  'Independent compiled ranges; midpoint is an Atlas representative selection, not a measured mean or joint '
  'sample. Porosity/saturation are unresolved; do not add pore space to this bulk reference.'),
 ('rock.quartzite',
  'Quartzite',
  'metamorphic',
  'bulk_reference',
  (),
  (('density',
    2.55,
    'g/cm3',
    'KAKOKO2023',
    'Table 3: quartzite density',
    (2.5, 2.6),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('heat_capacity',
    0.725,
    'J/g/K',
    'KAKOKO2023',
    'Table 3: quartzite specific heat',
    (0.62, 0.83),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('conductivity',
    4.3,
    'W/m/K',
    'KAKOKO2023',
    'Table 3: quartzite conductivity',
    (2.9, 5.7),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('thermal_expansion',
    11.0,
    'linear_micro/K_isotropic',
    'HUOTARI2004',
    'Table 3: Dane 1942 quartzite family',
    (11.0, 11.0),
    'isotropic_interval_secant',
    293.15,
    (293.15, 373.15),
    '3×linear as isotropic small-strain approximation over 20–100 C; not a crystalline tensor or instantaneous '
    'derivative.')),
  'Independent compiled ranges; midpoint is an Atlas representative selection, not a measured mean or joint '
  'sample. Porosity/saturation are unresolved; do not add pore space to this bulk reference.'),
 ('rock.schist',
  'Schist',
  'metamorphic',
  'bulk_reference',
  (),
  (('density',
    2.7,
    'g/cm3',
    'KAKOKO2023',
    'Table 3: schist density',
    (2.6, 2.8),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('heat_capacity',
    0.945,
    'J/g/K',
    'KAKOKO2023',
    'Table 3: schist specific heat',
    (0.79, 1.1),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('conductivity',
    2.55,
    'W/m/K',
    'KAKOKO2023',
    'Table 3: schist conductivity',
    (2.1, 3.0),
    'midpoint_of_reported_range',
    293.15,
    None,
    '')),
  'Independent compiled ranges; midpoint is an Atlas representative selection, not a measured mean or joint '
  'sample. Porosity/saturation are unresolved; do not add pore space to this bulk reference.'),
 ('rock.gneiss',
  'Gneiss',
  'metamorphic',
  'bulk_reference',
  (),
  (('density', 2.7, 'g/cm3', 'KAKOKO2023', 'Table 3: gneiss density', None, 'reported', 293.15, None, ''),
   ('heat_capacity',
    0.875,
    'J/g/K',
    'KAKOKO2023',
    'Table 3: gneiss specific heat',
    (0.77, 0.98),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('conductivity',
    2.9,
    'W/m/K',
    'KAKOKO2023',
    'Table 3: gneiss conductivity',
    (2.7, 3.1),
    'midpoint_of_reported_range',
    293.15,
    None,
    '')),
  'Independent compiled ranges; midpoint is an Atlas representative selection, not a measured mean or joint '
  'sample. Porosity/saturation are unresolved; do not add pore space to this bulk reference.'),
 ('rock.hornfels',
  'Hornfels',
  'metamorphic',
  'bulk_reference',
  (),
  (('density', 2.7, 'g/cm3', 'KAKOKO2023', 'Table 3: hornfels density', None, 'reported', 293.15, None, ''),
   ('heat_capacity',
    0.82,
    'J/g/K',
    'KAKOKO2023',
    'Table 3: hornfels specific heat',
    None,
    'reported',
    293.15,
    None,
    ''),
   ('conductivity',
    2.25,
    'W/m/K',
    'KAKOKO2023',
    'Table 3: hornfels conductivity',
    (1.5, 3.0),
    'midpoint_of_reported_range',
    293.15,
    None,
    '')),
  'Independent compiled ranges; midpoint is an Atlas representative selection, not a measured mean or joint '
  'sample. Porosity/saturation are unresolved; do not add pore space to this bulk reference.'),
 ('rock.soapstone',
  'Soapstone',
  'metamorphic',
  'bulk_reference',
  ('steatite',),
  (('density',
    2.85,
    'g/cm3',
    'KAKOKO2023',
    'Table 3: soapstone density',
    (2.7, 3.0),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('heat_capacity',
    1.025,
    'J/g/K',
    'KAKOKO2023',
    'Table 3: soapstone specific heat',
    (0.98, 1.07),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('conductivity',
    2.5,
    'W/m/K',
    'KAKOKO2023',
    'Table 3: soapstone conductivity',
    None,
    'reported',
    293.15,
    None,
    '')),
  'Independent compiled ranges; midpoint is an Atlas representative selection, not a measured mean or joint '
  'sample. Porosity/saturation are unresolved; do not add pore space to this bulk reference.'),
 ('rock.peridotite',
  'Peridotite',
  'mantle_ultramafic',
  'bulk_reference',
  (),
  (('density',
    3.19,
    'g/cm3',
    'LEE2015',
    'Table 8: peridotite selected row',
    None,
    'reported',
    293.15,
    None,
    ''),
   ('heat_capacity',
    1005,
    'J/kg/K',
    'LEE2015',
    'Table 8: peridotite selected 20 C row',
    None,
    'reported',
    293.15,
    None,
    ''),
   ('conductivity',
    4.0,
    'W/m/K',
    'ANDUJAR2016',
    'Table 1: peridotite typical conductivity',
    (3.8, 5.3),
    'reported',
    293.15,
    None,
    'Nominal room reference; precise saturation/temperature unresolved by this compilation.')),
  'Published reference rows from different samples/compilations, not a matched specimen. Where several cp rows '
  'exist the selected row is recorded, not averaged. Ambient mantle samples are not in-situ mantle laws.'),
 ('rock.harzburgite',
  'Harzburgite',
  'mantle_ultramafic',
  'bulk_reference',
  (),
  (('density',
    3.2,
    'g/cm3',
    'LEE2015',
    'Table 8: harzburgite selected row',
    None,
    'reported',
    293.15,
    None,
    ''),
   ('heat_capacity',
    759,
    'J/kg/K',
    'LEE2015',
    'Table 8: harzburgite selected 20 C row',
    None,
    'reported',
    293.15,
    None,
    '')),
  'Published reference rows from different samples/compilations, not a matched specimen. Where several cp rows '
  'exist the selected row is recorded, not averaged. Ambient mantle samples are not in-situ mantle laws.'),
 ('rock.lherzolite',
  'Lherzolite',
  'mantle_ultramafic',
  'bulk_reference',
  (),
  (('density', 3.2, 'g/cm3', 'LEE2015', 'Table 8: lherzolite selected row', None, 'reported', 293.15, None, ''),
   ('heat_capacity',
    778,
    'J/kg/K',
    'LEE2015',
    'Table 8: lherzolite selected 20 C row',
    None,
    'reported',
    293.15,
    None,
    '')),
  'Published reference rows from different samples/compilations, not a matched specimen. Where several cp rows '
  'exist the selected row is recorded, not averaged. Ambient mantle samples are not in-situ mantle laws.'),
 ('rock.pyroxenite',
  'Pyroxenite',
  'mantle_ultramafic',
  'bulk_reference',
  (),
  (('density',
    3.19,
    'g/cm3',
    'LEE2015',
    'Table 8: pyroxenite selected row',
    None,
    'reported',
    293.15,
    None,
    ''),
   ('heat_capacity',
    1000,
    'J/kg/K',
    'LEE2015',
    'Table 8: pyroxenite selected 20 C row',
    None,
    'reported',
    293.15,
    None,
    '')),
  'Published reference rows from different samples/compilations, not a matched specimen. Where several cp rows '
  'exist the selected row is recorded, not averaged. Ambient mantle samples are not in-situ mantle laws.'),
 ('rock.serpentinite',
  'Serpentinite',
  'metamorphic',
  'bulk_reference',
  (),
  (('density',
    2.54,
    'g/cm3',
    'LEE2015',
    'Table 8: serpentinite selected row',
    None,
    'reported',
    293.15,
    None,
    ''),
   ('heat_capacity',
    1005,
    'J/kg/K',
    'LEE2015',
    'Table 8: serpentinite selected 20 C row',
    None,
    'reported',
    293.15,
    None,
    ''),
   ('conductivity',
    2.59,
    'W/m/K',
    'LEE2015',
    'Table 7: serpentinite conductivity',
    (2.31, 2.87),
    'midpoint_of_reported_range',
    293.15,
    None,
    'Nominal room reference; precise saturation/temperature unresolved by this compilation.')),
  'Published reference rows from different samples/compilations, not a matched specimen. Where several cp rows '
  'exist the selected row is recorded, not averaged. Ambient mantle samples are not in-situ mantle laws.'),
 ('rock.phyllite',
  'Phyllite',
  'metamorphic',
  'bulk_reference',
  (),
  (('density', 2.72, 'g/cm3', 'LEE2015', 'Table 8: phyllite selected row', None, 'reported', 293.15, None, ''),
   ('heat_capacity',
    1090,
    'J/kg/K',
    'LEE2015',
    'Table 8: phyllite selected 20 C row',
    None,
    'reported',
    293.15,
    None,
    ''),
   ('conductivity',
    1.67,
    'W/m/K',
    'LEE2015',
    'Table 7: phyllite conductivity',
    None,
    'reported',
    293.15,
    None,
    'Nominal room reference; precise saturation/temperature unresolved by this compilation.')),
  'Published reference rows from different samples/compilations, not a matched specimen. Where several cp rows '
  'exist the selected row is recorded, not averaged. Ambient mantle samples are not in-situ mantle laws.'),
 ('rock.slate',
  'Slate',
  'metamorphic',
  'bulk_reference',
  (),
  (('density', 2.77, 'g/cm3', 'LEE2015', 'Table 8: slate selected row', None, 'reported', 293.15, None, ''),
   ('heat_capacity',
    1113,
    'J/kg/K',
    'LEE2015',
    'Table 8: slate selected 20 C row',
    None,
    'reported',
    293.15,
    None,
    ''),
   ('thermal_expansion',
    9.0,
    'linear_micro/K_isotropic',
    'HUOTARI2004',
    'Table 3: Dane 1942 slate family',
    (8.0, 10.0),
    'isotropic_interval_secant',
    293.15,
    (293.15, 373.15),
    '3×linear as isotropic small-strain approximation over 20–100 C; not a crystalline tensor or instantaneous '
    'derivative.')),
  'Published reference rows from different samples/compilations, not a matched specimen. Where several cp rows '
  'exist the selected row is recorded, not averaged. Ambient mantle samples are not in-situ mantle laws.'),
 ('rock.amphibolite',
  'Amphibolite',
  'metamorphic',
  'bulk_reference',
  (),
  (('density',
    3.01,
    'g/cm3',
    'LEE2015',
    'Table 8: amphibolite selected row',
    None,
    'reported',
    293.15,
    None,
    ''),
   ('heat_capacity',
    700,
    'J/kg/K',
    'LEE2015',
    'Table 8: amphibolite selected 20 C row',
    None,
    'reported',
    293.15,
    None,
    '')),
  'Published reference rows from different samples/compilations, not a matched specimen. Where several cp rows '
  'exist the selected row is recorded, not averaged. Ambient mantle samples are not in-situ mantle laws.'),
 ('rock.syenite',
  'Syenite',
  'igneous_intermediate',
  'bulk_reference',
  (),
  (('density', 2.82, 'g/cm3', 'LEE2015', 'Table 8: syenite selected row', None, 'reported', 293.15, None, ''),
   ('heat_capacity',
    460,
    'J/kg/K',
    'LEE2015',
    'Table 8: syenite selected 20 C row',
    None,
    'reported',
    293.15,
    None,
    ''),
   ('conductivity',
    2.82,
    'W/m/K',
    'LEE2015',
    'Table 7: syenite conductivity',
    (1.74, 3.9),
    'midpoint_of_reported_range',
    293.15,
    None,
    'Nominal room reference; precise saturation/temperature unresolved by this compilation.')),
  'Published reference rows from different samples/compilations, not a matched specimen. Where several cp rows '
  'exist the selected row is recorded, not averaged. Ambient mantle samples are not in-situ mantle laws.'),
 ('rock.pegmatite',
  'Pegmatite',
  'igneous_felsic',
  'bulk_reference',
  (),
  (('density', 2.7, 'g/cm3', 'LEE2015', 'Table 8: pegmatite selected row', None, 'reported', 293.15, None, ''),
   ('heat_capacity',
    710,
    'J/kg/K',
    'LEE2015',
    'Table 8: pegmatite selected 20 C row',
    None,
    'reported',
    293.15,
    None,
    '')),
  'Published reference rows from different samples/compilations, not a matched specimen. Where several cp rows '
  'exist the selected row is recorded, not averaged. Ambient mantle samples are not in-situ mantle laws.'),
 ('rock.marl',
  'Marl',
  'sedimentary_carbonate',
  'bulk_reference',
  (),
  (('density', 2.72, 'g/cm3', 'LEE2015', 'Table 8: marl selected row', None, 'reported', 293.15, None, ''),
   ('heat_capacity',
    950,
    'J/kg/K',
    'LEE2015',
    'Table 8: marl selected 20 C row',
    None,
    'reported',
    293.15,
    None,
    ''),
   ('conductivity',
    2.1,
    'W/m/K',
    'LEE2015',
    'Table 6: marl 2.1 +/- 0.7',
    (1.4, 2.8),
    'reported',
    293.15,
    None,
    'Nominal room reference; precise saturation/temperature unresolved by this compilation.')),
  'Published reference rows from different samples/compilations, not a matched specimen. Where several cp rows '
  'exist the selected row is recorded, not averaged. Ambient mantle samples are not in-situ mantle laws.'),
 ('rock.siltstone',
  'Siltstone',
  'sedimentary_siliciclastic',
  'bulk_reference',
  (),
  (('density', 2.68, 'g/cm3', 'LEE2015', 'Table 8: siltstone selected row', None, 'reported', 293.15, None, ''),
   ('heat_capacity',
    910,
    'J/kg/K',
    'LEE2015',
    'Table 8: siltstone selected 20 C row',
    None,
    'reported',
    293.15,
    None,
    ''),
   ('conductivity',
    2.2,
    'W/m/K',
    'ANDUJAR2016',
    'Table 1: siltstone/argillite typical',
    (1.1, 3.5),
    'reported',
    293.15,
    None,
    'Nominal room reference; precise saturation/temperature unresolved by this compilation.')),
  'Published reference rows from different samples/compilations, not a matched specimen. Where several cp rows '
  'exist the selected row is recorded, not averaged. Ambient mantle samples are not in-situ mantle laws.'),
 ('rock.argillite',
  'Argillite',
  'sedimentary_siliciclastic',
  'bulk_reference',
  (),
  (('density', 2.69, 'g/cm3', 'LEE2015', 'Table 8: argillite selected row', None, 'reported', 293.15, None, ''),
   ('heat_capacity',
    850,
    'J/kg/K',
    'LEE2015',
    'Table 8: argillite selected 20 C row',
    None,
    'reported',
    293.15,
    None,
    ''),
   ('conductivity',
    2.2,
    'W/m/K',
    'ANDUJAR2016',
    'Table 1: siltstone/argillite typical',
    (1.1, 3.5),
    'reported',
    293.15,
    None,
    'Nominal room reference; precise saturation/temperature unresolved by this compilation.')),
  'Published reference rows from different samples/compilations, not a matched specimen. Where several cp rows '
  'exist the selected row is recorded, not averaged. Ambient mantle samples are not in-situ mantle laws.'),
 ('rock.tuff',
  'Tuff',
  'igneous_volcaniclastic',
  'bulk_reference',
  (),
  (('density', 2.69, 'g/cm3', 'LEE2015', 'Table 8: tuff selected row', None, 'reported', 293.15, None, ''),
   ('heat_capacity',
    795,
    'J/kg/K',
    'LEE2015',
    'Table 8: tuff selected 20 C row',
    None,
    'reported',
    293.15,
    None,
    ''),
   ('conductivity',
    1.7,
    'W/m/K',
    'LEE2015',
    'Table 6: tuff 1.7 +/- 0.3',
    (1.4, 2.0),
    'reported',
    293.15,
    None,
    'Nominal room reference; precise saturation/temperature unresolved by this compilation.')),
  'Published reference rows from different samples/compilations, not a matched specimen. Where several cp rows '
  'exist the selected row is recorded, not averaged. Ambient mantle samples are not in-situ mantle laws.'),
 ('rock.coal',
  'Coal',
  'sedimentary_organic',
  'bulk_reference',
  (),
  (('density', 1.35, 'g/cm3', 'LEE2015', 'Table 8: coal selected row', None, 'reported', 293.15, None, ''),
   ('heat_capacity',
    1300,
    'J/kg/K',
    'LEE2015',
    'Table 8: coal selected 20 C row',
    None,
    'reported',
    293.15,
    None,
    ''),
   ('conductivity',
    0.3,
    'W/m/K',
    'LEE2015',
    'Table 6: coal 0.3 +/- 0.1',
    (0.2, 0.4),
    'reported',
    293.15,
    None,
    'Nominal room reference; precise saturation/temperature unresolved by this compilation.')),
  'Published reference rows from different samples/compilations, not a matched specimen. Where several cp rows '
  'exist the selected row is recorded, not averaged. Ambient mantle samples are not in-situ mantle laws.'),
 ('rock.anhydrite',
  'Anhydrite',
  'sedimentary_evaporite',
  'bulk_reference',
  (),
  (('density', 2.95, 'g/cm3', 'LEE2015', 'Table 8: anhydrite selected row', None, 'reported', 293.15, None, ''),
   ('heat_capacity',
    590,
    'J/kg/K',
    'LEE2015',
    'Table 8: anhydrite selected 20 C row',
    None,
    'reported',
    293.15,
    None,
    ''),
   ('conductivity',
    4.76,
    'W/m/K',
    'LEE2015',
    'Table 1: anhydrite conductivity',
    None,
    'reported',
    293.15,
    None,
    'Nominal room reference; precise saturation/temperature unresolved by this compilation.')),
  'Published reference rows from different samples/compilations, not a matched specimen. Where several cp rows '
  'exist the selected row is recorded, not averaged. Ambient mantle samples are not in-situ mantle laws.'),
 ('rock.gypsum',
  'Gypsum',
  'sedimentary_evaporite',
  'bulk_reference',
  (),
  (('density', 2.37, 'g/cm3', 'LEE2015', 'Table 8: gypsum selected row', None, 'reported', 293.15, None, ''),
   ('heat_capacity',
    1010,
    'J/kg/K',
    'LEE2015',
    'Table 8: gypsum selected 20 C row',
    None,
    'reported',
    293.15,
    None,
    ''),
   ('conductivity',
    1.29,
    'W/m/K',
    'WATER2024',
    'Table 6: gypsum conductivity',
    None,
    'reported',
    293.15,
    None,
    'Nominal room reference; precise saturation/temperature unresolved by this compilation.')),
  'Published reference rows from different samples/compilations, not a matched specimen. Where several cp rows '
  'exist the selected row is recorded, not averaged. Ambient mantle samples are not in-situ mantle laws.'),
 ('rock.rock_salt',
  'Rock salt',
  'sedimentary_evaporite',
  'bulk_reference',
  (),
  (('density', 2.16, 'g/cm3', 'LEE2015', 'Table 8: rock_salt selected row', None, 'reported', 293.15, None, ''),
   ('heat_capacity',
    880,
    'J/kg/K',
    'LEE2015',
    'Table 8: rock_salt selected 20 C row',
    None,
    'reported',
    293.15,
    None,
    ''),
   ('conductivity',
    5.4,
    'W/m/K',
    'ANDUJAR2016',
    'Table 1: salt typical conductivity',
    (5.3, 6.4),
    'reported',
    293.15,
    None,
    'Nominal room reference; precise saturation/temperature unresolved by this compilation.')),
  'Published reference rows from different samples/compilations, not a matched specimen. Where several cp rows '
  'exist the selected row is recorded, not averaged. Ambient mantle samples are not in-situ mantle laws.'),
 ('rock.aluminous_shale',
  'Aluminous shale',
  'sedimentary_siliciclastic',
  'bulk_reference',
  (),
  (('density',
    2.6,
    'g/cm3',
    'WATER2024',
    'Table 6: shale density',
    (2.4, 2.8),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('heat_capacity',
    1.16,
    'kJ/kg/K',
    'WATER2024',
    'Table 6: shale heat capacity',
    (0.88, 1.44),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('conductivity',
    2.4,
    'W/m/K',
    'WATER2024',
    'Table 6: shale conductivity',
    (0.55, 4.25),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('heat_production',
    2.9,
    'microW/m3',
    'HASTEROK2018',
    'Section 5.3: aluminous_shale population representative',
    None,
    'population_representative',
    293.15,
    None,
    'Present-day sample population, not a universal rock constant or radioactive decay history.')),
  'Thermophysical shale-family proxy; source-rate populations distinguish composition. No local chemical '
  'calibration is implied.'),
 ('rock.iron_rich_shale',
  'Iron rich shale',
  'sedimentary_siliciclastic',
  'bulk_reference',
  (),
  (('density',
    2.6,
    'g/cm3',
    'WATER2024',
    'Table 6: shale density',
    (2.4, 2.8),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('heat_capacity',
    1.16,
    'kJ/kg/K',
    'WATER2024',
    'Table 6: shale heat capacity',
    (0.88, 1.44),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('conductivity',
    2.4,
    'W/m/K',
    'WATER2024',
    'Table 6: shale conductivity',
    (0.55, 4.25),
    'midpoint_of_reported_range',
    293.15,
    None,
    ''),
   ('heat_production',
    1.7,
    'microW/m3',
    'HASTEROK2018',
    'Section 5.3: iron_rich_shale population representative',
    None,
    'population_representative',
    293.15,
    None,
    'Present-day sample population, not a universal rock constant or radioactive decay history.')),
  'Thermophysical shale-family proxy; source-rate populations distinguish composition. No local chemical '
  'calibration is implied.'),
 ('mineral.quartz',
  'Quartz',
  'rock_forming_mineral',
  'grain',
  (),
  (('density',
    2.648,
    'g/cm3',
    'GOTO2008',
    'Table 3: quartz, density',
    None,
    'reported',
    293.15,
    None,
    'Room reference; upstream Johnson & Olhoeft 1984.'),
   ('conductivity',
    7.69,
    'W/m/K',
    'GOTO2008',
    'Table 3: quartz, conductivity',
    None,
    'reported',
    293.15,
    None,
    'Scalar constituent reference; not an orientation-resolved tensor.'),
   ('heat_capacity',
    741,
    'J/kg/K',
    'GOTO2008',
    'Table 3: quartz, specific heat',
    None,
    'compiled_or_derived_reference',
    293.15,
    None,
    'Includes derived entries in the original table; room-condition reference, nominal 293.15 K.'),
   ('thermal_expansion',
    4.98,
    '1e-5/K',
    'LEE2015',
    'Table 5: quartz, volume expansion',
    None,
    'interval_secant',
    293.15,
    (293.15, 673.15),
    '20–400 C mean volume expansion; not room-temperature derivative.')),
  'Pure constituent/class reference. No pores included. Orientation and detailed clay composition are not '
  'modelled.'),
 ('mineral.albite',
  'Albite',
  'rock_forming_mineral',
  'grain',
  (),
  (('density',
    2.62,
    'g/cm3',
    'GOTO2008',
    'Table 3: albite, density',
    None,
    'reported',
    293.15,
    None,
    'Room reference; upstream Johnson & Olhoeft 1984.'),
   ('conductivity',
    2.2,
    'W/m/K',
    'GOTO2008',
    'Table 3: albite, conductivity',
    None,
    'reported',
    293.15,
    None,
    'Scalar constituent reference; not an orientation-resolved tensor.'),
   ('heat_capacity',
    776,
    'J/kg/K',
    'GOTO2008',
    'Table 3: albite, specific heat',
    None,
    'compiled_or_derived_reference',
    293.15,
    None,
    'Includes derived entries in the original table; room-condition reference, nominal 293.15 K.'),
   ('thermal_expansion',
    2.24,
    '1e-5/K',
    'LEE2015',
    'Table 5: albite, volume expansion',
    None,
    'interval_secant',
    293.15,
    (293.15, 673.15),
    '20–400 C mean volume expansion; not room-temperature derivative.')),
  'Pure constituent/class reference. No pores included. Orientation and detailed clay composition are not '
  'modelled.'),
 ('mineral.anorthite',
  'Anorthite',
  'rock_forming_mineral',
  'grain',
  (),
  (('density',
    2.76,
    'g/cm3',
    'GOTO2008',
    'Table 3: anorthite, density',
    None,
    'reported',
    293.15,
    None,
    'Room reference; upstream Johnson & Olhoeft 1984.'),
   ('conductivity',
    1.68,
    'W/m/K',
    'GOTO2008',
    'Table 3: anorthite, conductivity',
    None,
    'reported',
    293.15,
    None,
    'Scalar constituent reference; not an orientation-resolved tensor.'),
   ('heat_capacity',
    745,
    'J/kg/K',
    'GOTO2008',
    'Table 3: anorthite, specific heat',
    None,
    'compiled_or_derived_reference',
    293.15,
    None,
    'Includes derived entries in the original table; room-condition reference, nominal 293.15 K.'),
   ('thermal_expansion',
    1.51,
    '1e-5/K',
    'LEE2015',
    'Table 5: anorthite, volume expansion',
    None,
    'interval_secant',
    293.15,
    (293.15, 673.15),
    '20–400 C mean volume expansion; not room-temperature derivative.')),
  'Pure constituent/class reference. No pores included. Orientation and detailed clay composition are not '
  'modelled.'),
 ('mineral.orthoclase',
  'Orthoclase',
  'rock_forming_mineral',
  'grain',
  (),
  (('density',
    2.57,
    'g/cm3',
    'GOTO2008',
    'Table 3: orthoclase, density',
    None,
    'reported',
    293.15,
    None,
    'Room reference; upstream Johnson & Olhoeft 1984.'),
   ('conductivity',
    2.32,
    'W/m/K',
    'GOTO2008',
    'Table 3: orthoclase, conductivity',
    None,
    'reported',
    293.15,
    None,
    'Scalar constituent reference; not an orientation-resolved tensor.'),
   ('heat_capacity',
    707,
    'J/kg/K',
    'GOTO2008',
    'Table 3: orthoclase, specific heat',
    None,
    'compiled_or_derived_reference',
    293.15,
    None,
    'Includes derived entries in the original table; room-condition reference, nominal 293.15 K.'),
   ('thermal_expansion',
    1.54,
    '1e-5/K',
    'LEE2015',
    'Table 5: orthoclase, volume expansion',
    None,
    'interval_secant',
    293.15,
    (293.15, 673.15),
    '20–400 C mean volume expansion; not room-temperature derivative.')),
  'Pure constituent/class reference. No pores included. Orientation and detailed clay composition are not '
  'modelled.'),
 ('mineral.muscovite',
  'Muscovite',
  'rock_forming_mineral',
  'grain',
  (),
  (('density',
    2.831,
    'g/cm3',
    'GOTO2008',
    'Table 3: muscovite, density',
    None,
    'reported',
    293.15,
    None,
    'Room reference; upstream Johnson & Olhoeft 1984.'),
   ('conductivity',
    2.32,
    'W/m/K',
    'GOTO2008',
    'Table 3: muscovite, conductivity',
    None,
    'reported',
    293.15,
    None,
    'Scalar constituent reference; not an orientation-resolved tensor.'),
   ('heat_capacity',
    796,
    'J/kg/K',
    'GOTO2008',
    'Table 3: muscovite, specific heat',
    None,
    'compiled_or_derived_reference',
    293.15,
    None,
    'Includes derived entries in the original table; room-condition reference, nominal 293.15 K.')),
  'Pure constituent/class reference. No pores included. Orientation and detailed clay composition are not '
  'modelled.'),
 ('mineral.illite',
  'Illite',
  'rock_forming_mineral',
  'grain',
  (),
  (('density',
    2.66,
    'g/cm3',
    'GOTO2008',
    'Table 3: illite, density',
    None,
    'reported',
    293.15,
    None,
    'Room reference; upstream Johnson & Olhoeft 1984.'),
   ('conductivity',
    1.85,
    'W/m/K',
    'GOTO2008',
    'Table 3: illite, conductivity',
    None,
    'reported',
    293.15,
    None,
    'Scalar constituent reference; not an orientation-resolved tensor.'),
   ('heat_capacity',
    808,
    'J/kg/K',
    'GOTO2008',
    'Table 3: illite, specific heat',
    None,
    'compiled_or_derived_reference',
    293.15,
    None,
    'Includes derived entries in the original table; room-condition reference, nominal 293.15 K.')),
  'Pure constituent/class reference. No pores included. Orientation and detailed clay composition are not '
  'modelled.'),
 ('mineral.smectite',
  'Smectite',
  'rock_forming_mineral',
  'grain',
  (),
  (('density',
    2.608,
    'g/cm3',
    'GOTO2008',
    'Table 3: smectite, density',
    None,
    'reported',
    293.15,
    None,
    'Room reference; upstream Johnson & Olhoeft 1984.'),
   ('conductivity',
    1.88,
    'W/m/K',
    'GOTO2008',
    'Table 3: smectite, conductivity',
    None,
    'reported',
    293.15,
    None,
    'Scalar constituent reference; not an orientation-resolved tensor.'),
   ('heat_capacity',
    795,
    'J/kg/K',
    'GOTO2008',
    'Table 3: smectite, specific heat',
    None,
    'compiled_or_derived_reference',
    293.15,
    None,
    'Includes derived entries in the original table; room-condition reference, nominal 293.15 K.')),
  'Pure constituent/class reference. No pores included. Orientation and detailed clay composition are not '
  'modelled.'),
 ('mineral.chlorite',
  'Chlorite',
  'rock_forming_mineral',
  'grain',
  (),
  (('density',
    2.8,
    'g/cm3',
    'GOTO2008',
    'Table 3: chlorite, density',
    None,
    'reported',
    293.15,
    None,
    'Room reference; upstream Johnson & Olhoeft 1984.'),
   ('conductivity',
    5.15,
    'W/m/K',
    'GOTO2008',
    'Table 3: chlorite, conductivity',
    None,
    'reported',
    293.15,
    None,
    'Scalar constituent reference; not an orientation-resolved tensor.'),
   ('heat_capacity',
    818,
    'J/kg/K',
    'GOTO2008',
    'Table 3: chlorite, specific heat',
    None,
    'compiled_or_derived_reference',
    293.15,
    None,
    'Includes derived entries in the original table; room-condition reference, nominal 293.15 K.')),
  'Pure constituent/class reference. No pores included. Orientation and detailed clay composition are not '
  'modelled.'),
 ('mineral.calcite',
  'Calcite',
  'rock_forming_mineral',
  'grain',
  (),
  (('density',
    2.71,
    'g/cm3',
    'GOTO2008',
    'Table 3: calcite, density',
    None,
    'reported',
    293.15,
    None,
    'Room reference; upstream Johnson & Olhoeft 1984.'),
   ('conductivity',
    3.59,
    'W/m/K',
    'GOTO2008',
    'Table 3: calcite, conductivity',
    None,
    'reported',
    293.15,
    None,
    'Scalar constituent reference; not an orientation-resolved tensor.'),
   ('heat_capacity',
    820,
    'J/kg/K',
    'GOTO2008',
    'Table 3: calcite, specific heat',
    None,
    'compiled_or_derived_reference',
    293.15,
    None,
    'Includes derived entries in the original table; room-condition reference, nominal 293.15 K.'),
   ('thermal_expansion',
    2.01,
    '1e-5/K',
    'LEE2015',
    'Table 5: calcite, volume expansion',
    None,
    'interval_secant',
    293.15,
    (293.15, 673.15),
    '20–400 C mean volume expansion; not room-temperature derivative.')),
  'Pure constituent/class reference. No pores included. Orientation and detailed clay composition are not '
  'modelled.'),
 ('mineral.microcline',
  'Microcline',
  'rock_forming_mineral',
  'grain',
  (),
  (('density', 2.56, 'g/cm3', 'LEE2015', 'Table 5: microcline, density', None, 'reported', 293.15, None, ''),
   ('thermal_expansion',
    1.79,
    '1e-5/K',
    'LEE2015',
    'Table 5: microcline, volume expansion',
    None,
    'interval_secant',
    293.15,
    (293.15, 673.15),
    'Single-crystal secant over 20–400 C; explicitly NOT instantaneous alpha at 20 C.'),
   ('conductivity',
    2.49,
    'W/m/K',
    'LEE2015',
    'Table 1: microcline, conductivity',
    None,
    'reported',
    293.15,
    None,
    'Room-condition scalar reference; directional dependence omitted.'),
   ('heat_capacity',
    0.68,
    'kJ/kg/K',
    'LEE2015',
    'Table 1: microcline, specific heat',
    None,
    'reported',
    273.15,
    None,
    'Most table-1 cp values are at 0 C; specified exceptions retained, never promoted to 20 C.')),
  'Separate reference temperatures/intervals are intentional. A phase identity does not certify thermal-law '
  'completeness.'),
 ('mineral.forsterite',
  'Forsterite',
  'rock_forming_mineral',
  'grain',
  (),
  (('density', 3.214, 'g/cm3', 'LEE2015', 'Table 5: forsterite, density', None, 'reported', 293.15, None, ''),
   ('thermal_expansion',
    3.26,
    '1e-5/K',
    'LEE2015',
    'Table 5: forsterite, volume expansion',
    None,
    'interval_secant',
    293.15,
    (293.15, 673.15),
    'Single-crystal secant over 20–400 C; explicitly NOT instantaneous alpha at 20 C.')),
  'Separate reference temperatures/intervals are intentional. A phase identity does not certify thermal-law '
  'completeness.'),
 ('mineral.fayalite',
  'Fayalite',
  'rock_forming_mineral',
  'grain',
  (),
  (('density', 4.393, 'g/cm3', 'LEE2015', 'Table 5: fayalite, density', None, 'reported', 293.15, None, ''),
   ('thermal_expansion',
    2.84,
    '1e-5/K',
    'LEE2015',
    'Table 5: fayalite, volume expansion',
    None,
    'interval_secant',
    293.15,
    (293.15, 673.15),
    'Single-crystal secant over 20–400 C; explicitly NOT instantaneous alpha at 20 C.')),
  'Separate reference temperatures/intervals are intentional. A phase identity does not certify thermal-law '
  'completeness.'),
 ('mineral.enstatite',
  'Enstatite',
  'rock_forming_mineral',
  'grain',
  (),
  (('density', 3.194, 'g/cm3', 'LEE2015', 'Table 5: enstatite, density', None, 'reported', 293.15, None, ''),
   ('thermal_expansion',
    2.77,
    '1e-5/K',
    'LEE2015',
    'Table 5: enstatite, volume expansion',
    None,
    'interval_secant',
    293.15,
    (293.15, 673.15),
    'Single-crystal secant over 20–400 C; explicitly NOT instantaneous alpha at 20 C.'),
   ('conductivity',
    4.34,
    'W/m/K',
    'LEE2015',
    'Table 1: enstatite, conductivity',
    None,
    'reported',
    293.15,
    None,
    'Room-condition scalar reference; directional dependence omitted.'),
   ('heat_capacity',
    0.8,
    'kJ/kg/K',
    'LEE2015',
    'Table 1: enstatite, specific heat',
    None,
    'reported',
    333.15,
    None,
    'Most table-1 cp values are at 0 C; specified exceptions retained, never promoted to 20 C.')),
  'Separate reference temperatures/intervals are intentional. A phase identity does not certify thermal-law '
  'completeness.'),
 ('mineral.diopside',
  'Diopside',
  'rock_forming_mineral',
  'grain',
  (),
  (('density', 3.277, 'g/cm3', 'LEE2015', 'Table 5: diopside, density', None, 'reported', 293.15, None, ''),
   ('thermal_expansion',
    2.51,
    '1e-5/K',
    'LEE2015',
    'Table 5: diopside, volume expansion',
    None,
    'interval_secant',
    293.15,
    (293.15, 673.15),
    'Single-crystal secant over 20–400 C; explicitly NOT instantaneous alpha at 20 C.'),
   ('conductivity',
    5.02,
    'W/m/K',
    'LEE2015',
    'Table 1: diopside, conductivity',
    None,
    'reported',
    293.15,
    None,
    'Room-condition scalar reference; directional dependence omitted.'),
   ('heat_capacity',
    0.69,
    'kJ/kg/K',
    'LEE2015',
    'Table 1: diopside, specific heat',
    None,
    'reported',
    273.15,
    None,
    'Most table-1 cp values are at 0 C; specified exceptions retained, never promoted to 20 C.')),
  'Separate reference temperatures/intervals are intentional. A phase identity does not certify thermal-law '
  'completeness.'),
 ('mineral.augite',
  'Augite',
  'rock_forming_mineral',
  'grain',
  (),
  (('density', 3.41, 'g/cm3', 'LEE2015', 'Table 5: augite, density', None, 'reported', 293.15, None, ''),
   ('thermal_expansion',
    2.19,
    '1e-5/K',
    'LEE2015',
    'Table 5: augite, volume expansion',
    None,
    'interval_secant',
    293.15,
    (293.15, 673.15),
    'Single-crystal secant over 20–400 C; explicitly NOT instantaneous alpha at 20 C.'),
   ('conductivity',
    3.82,
    'W/m/K',
    'LEE2015',
    'Table 1: augite, conductivity',
    None,
    'reported',
    293.15,
    None,
    'Room-condition scalar reference; directional dependence omitted.')),
  'Separate reference temperatures/intervals are intentional. A phase identity does not certify thermal-law '
  'completeness.'),
 ('mineral.hornblende',
  'Hornblende',
  'rock_forming_mineral',
  'grain',
  (),
  (('density', 3.37, 'g/cm3', 'LEE2015', 'Table 5: hornblende, density', None, 'reported', 293.15, None, ''),
   ('thermal_expansion',
    2.56,
    '1e-5/K',
    'LEE2015',
    'Table 5: hornblende, volume expansion',
    None,
    'interval_secant',
    293.15,
    (293.15, 673.15),
    'Single-crystal secant over 20–400 C; explicitly NOT instantaneous alpha at 20 C.'),
   ('conductivity',
    2.85,
    'W/m/K',
    'LEE2015',
    'Table 1: hornblende, conductivity',
    None,
    'reported',
    293.15,
    None,
    'Room-condition scalar reference; directional dependence omitted.')),
  'Separate reference temperatures/intervals are intentional. A phase identity does not certify thermal-law '
  'completeness.'),
 ('mineral.almandine',
  'Almandine',
  'rock_forming_mineral',
  'grain',
  (),
  (('density', 4.318, 'g/cm3', 'LEE2015', 'Table 5: almandine, density', None, 'reported', 293.15, None, ''),
   ('thermal_expansion',
    2.11,
    '1e-5/K',
    'LEE2015',
    'Table 5: almandine, volume expansion',
    None,
    'interval_secant',
    293.15,
    (293.15, 673.15),
    'Single-crystal secant over 20–400 C; explicitly NOT instantaneous alpha at 20 C.'),
   ('conductivity',
    3.31,
    'W/m/K',
    'LEE2015',
    'Table 1: almandine, conductivity',
    None,
    'reported',
    293.15,
    None,
    'Room-condition scalar reference; directional dependence omitted.')),
  'Separate reference temperatures/intervals are intentional. A phase identity does not certify thermal-law '
  'completeness.'),
 ('mineral.magnetite',
  'Magnetite',
  'rock_forming_mineral',
  'grain',
  (),
  (('density', 5.2, 'g/cm3', 'LEE2015', 'Table 5: magnetite, density', None, 'reported', 293.15, None, ''),
   ('thermal_expansion',
    3.5,
    '1e-5/K',
    'LEE2015',
    'Table 5: magnetite, volume expansion',
    None,
    'interval_secant',
    293.15,
    (293.15, 673.15),
    'Single-crystal secant over 20–400 C; explicitly NOT instantaneous alpha at 20 C.'),
   ('conductivity',
    5.1,
    'W/m/K',
    'LEE2015',
    'Table 1: magnetite, conductivity',
    None,
    'reported',
    293.15,
    None,
    'Room-condition scalar reference; directional dependence omitted.'),
   ('heat_capacity',
    0.6,
    'kJ/kg/K',
    'LEE2015',
    'Table 1: magnetite, specific heat',
    None,
    'reported',
    273.15,
    None,
    'Most table-1 cp values are at 0 C; specified exceptions retained, never promoted to 20 C.')),
  'Separate reference temperatures/intervals are intentional. A phase identity does not certify thermal-law '
  'completeness.'),
 ('mineral.hematite',
  'Hematite',
  'rock_forming_mineral',
  'grain',
  (),
  (('density', 5.275, 'g/cm3', 'LEE2015', 'Table 5: hematite, density', None, 'reported', 293.15, None, ''),
   ('thermal_expansion',
    3.1,
    '1e-5/K',
    'LEE2015',
    'Table 5: hematite, volume expansion',
    None,
    'interval_secant',
    293.15,
    (293.15, 673.15),
    'Single-crystal secant over 20–400 C; explicitly NOT instantaneous alpha at 20 C.'),
   ('conductivity',
    11.3,
    'W/m/K',
    'LEE2015',
    'Table 1: hematite, conductivity',
    None,
    'reported',
    293.15,
    None,
    'Room-condition scalar reference; directional dependence omitted.'),
   ('heat_capacity',
    0.61,
    'kJ/kg/K',
    'LEE2015',
    'Table 1: hematite, specific heat',
    None,
    'reported',
    273.15,
    None,
    'Most table-1 cp values are at 0 C; specified exceptions retained, never promoted to 20 C.')),
  'Separate reference temperatures/intervals are intentional. A phase identity does not certify thermal-law '
  'completeness.'),
 ('mineral.pyrite',
  'Pyrite',
  'rock_forming_mineral',
  'grain',
  (),
  (('density', 5.016, 'g/cm3', 'LEE2015', 'Table 5: pyrite, density', None, 'reported', 293.15, None, ''),
   ('thermal_expansion',
    3.4,
    '1e-5/K',
    'LEE2015',
    'Table 5: pyrite, volume expansion',
    None,
    'interval_secant',
    293.15,
    (293.15, 673.15),
    'Single-crystal secant over 20–400 C; explicitly NOT instantaneous alpha at 20 C.'),
   ('conductivity',
    19.2,
    'W/m/K',
    'LEE2015',
    'Table 1: pyrite, conductivity',
    None,
    'reported',
    293.15,
    None,
    'Room-condition scalar reference; directional dependence omitted.'),
   ('heat_capacity',
    0.5,
    'kJ/kg/K',
    'LEE2015',
    'Table 1: pyrite, specific heat',
    None,
    'reported',
    273.15,
    None,
    'Most table-1 cp values are at 0 C; specified exceptions retained, never promoted to 20 C.')),
  'Separate reference temperatures/intervals are intentional. A phase identity does not certify thermal-law '
  'completeness.'),
 ('mineral.kyanite',
  'Kyanite',
  'rock_forming_mineral',
  'grain',
  (),
  (('density', 3.675, 'g/cm3', 'LEE2015', 'Table 5: kyanite, density', None, 'reported', 293.15, None, ''),
   ('thermal_expansion',
    2.35,
    '1e-5/K',
    'LEE2015',
    'Table 5: kyanite, volume expansion',
    None,
    'interval_secant',
    293.15,
    (293.15, 673.15),
    'Single-crystal secant over 20–400 C; explicitly NOT instantaneous alpha at 20 C.'),
   ('conductivity',
    14.2,
    'W/m/K',
    'LEE2015',
    'Table 1: kyanite, conductivity',
    None,
    'reported',
    293.15,
    None,
    'Room-condition scalar reference; directional dependence omitted.'),
   ('heat_capacity',
    0.7,
    'kJ/kg/K',
    'LEE2015',
    'Table 1: kyanite, specific heat',
    None,
    'reported',
    273.15,
    None,
    'Most table-1 cp values are at 0 C; specified exceptions retained, never promoted to 20 C.')),
  'Separate reference temperatures/intervals are intentional. A phase identity does not certify thermal-law '
  'completeness.'),
 ('mineral.andalusite',
  'Andalusite',
  'rock_forming_mineral',
  'grain',
  (),
  (('density', 3.0915, 'g/cm3', 'LEE2015', 'Table 5: andalusite, density', None, 'reported', 293.15, None, ''),
   ('thermal_expansion',
    2.82,
    '1e-5/K',
    'LEE2015',
    'Table 5: andalusite, volume expansion',
    None,
    'interval_secant',
    293.15,
    (293.15, 673.15),
    'Single-crystal secant over 20–400 C; explicitly NOT instantaneous alpha at 20 C.'),
   ('conductivity',
    7.57,
    'W/m/K',
    'LEE2015',
    'Table 1: andalusite, conductivity',
    None,
    'reported',
    293.15,
    None,
    'Room-condition scalar reference; directional dependence omitted.'),
   ('heat_capacity',
    0.77,
    'kJ/kg/K',
    'LEE2015',
    'Table 1: andalusite, specific heat',
    None,
    'reported',
    273.15,
    None,
    'Most table-1 cp values are at 0 C; specified exceptions retained, never promoted to 20 C.')),
  'Separate reference temperatures/intervals are intentional. A phase identity does not certify thermal-law '
  'completeness.'),
 ('mineral.sillimanite',
  'Sillimanite',
  'rock_forming_mineral',
  'grain',
  (),
  (('density', 3.247, 'g/cm3', 'LEE2015', 'Table 5: sillimanite, density', None, 'reported', 293.15, None, ''),
   ('thermal_expansion',
    1.4,
    '1e-5/K',
    'LEE2015',
    'Table 5: sillimanite, volume expansion',
    None,
    'interval_secant',
    293.15,
    (293.15, 673.15),
    'Single-crystal secant over 20–400 C; explicitly NOT instantaneous alpha at 20 C.'),
   ('conductivity',
    9.09,
    'W/m/K',
    'LEE2015',
    'Table 1: sillimanite, conductivity',
    None,
    'reported',
    293.15,
    None,
    'Room-condition scalar reference; directional dependence omitted.'),
   ('heat_capacity',
    0.743,
    'kJ/kg/K',
    'LEE2015',
    'Table 1: sillimanite, specific heat',
    None,
    'reported',
    273.15,
    None,
    'Most table-1 cp values are at 0 C; specified exceptions retained, never promoted to 20 C.')),
  'Separate reference temperatures/intervals are intentional. A phase identity does not certify thermal-law '
  'completeness.'),
 ('mineral.aragonite',
  'Aragonite',
  'rock_forming_mineral',
  'grain',
  (),
  (('density', 2.93, 'g/cm3', 'LEE2015', 'Table 5: aragonite, density', None, 'reported', 293.15, None, ''),
   ('thermal_expansion',
    6.53,
    '1e-5/K',
    'LEE2015',
    'Table 5: aragonite, volume expansion',
    None,
    'interval_secant',
    293.15,
    (293.15, 673.15),
    'Single-crystal secant over 20–400 C; explicitly NOT instantaneous alpha at 20 C.'),
   ('conductivity',
    2.23,
    'W/m/K',
    'LEE2015',
    'Table 1: aragonite, conductivity',
    None,
    'reported',
    293.15,
    None,
    'Room-condition scalar reference; directional dependence omitted.'),
   ('heat_capacity',
    0.78,
    'kJ/kg/K',
    'LEE2015',
    'Table 1: aragonite, specific heat',
    None,
    'reported',
    273.15,
    None,
    'Most table-1 cp values are at 0 C; specified exceptions retained, never promoted to 20 C.')),
  'Separate reference temperatures/intervals are intentional. A phase identity does not certify thermal-law '
  'completeness.'),
 ('mineral.halite',
  'Halite',
  'rock_forming_mineral',
  'grain',
  (),
  (('density', 2.163, 'g/cm3', 'LEE2015', 'Table 5: halite, density', None, 'reported', 293.15, None, ''),
   ('thermal_expansion',
    13.83,
    '1e-5/K',
    'LEE2015',
    'Table 5: halite, volume expansion',
    None,
    'interval_secant',
    293.15,
    (293.15, 673.15),
    'Single-crystal secant over 20–400 C; explicitly NOT instantaneous alpha at 20 C.')),
  'Separate reference temperatures/intervals are intentional. A phase identity does not certify thermal-law '
  'completeness.'),
 ('fluid.fresh_water',
  'Liquid fresh water',
  'fluid',
  'fluid',
  ('water',),
  (('density', 998.2, 'kg/m3', 'WATER2019', 'Table 2: liquid water', None, 'reported', 293.15, None, ''),
   ('conductivity', 0.6, 'W/m/K', 'WATER2019', 'Table 2: liquid water', None, 'reported', 293.15, None, ''),
   ('heat_capacity',
    4182.0,
    'J/kg/K',
    'WATER2019',
    'Table 2: liquid water',
    None,
    'reported',
    293.15,
    None,
    '')),
  'Rounded engineering liquid-water reference at nominal room conditions. No salinity, phase transition, '
  'pressure or temperature law.'),
 ('fluid.seawater',
  'Seawater reference',
  'fluid',
  'fluid',
  (),
  (('density', 1.024, 'g/cm3', 'GOTO2008', 'Table 3: sea water', None, 'reported', 293.15, None, ''),
   ('conductivity', 0.596, 'W/m/K', 'GOTO2008', 'Table 3: sea water', None, 'reported', 293.15, None, ''),
   ('heat_capacity', 3993.0, 'J/kg/K', 'GOTO2008', 'Table 3: sea water', None, 'reported', 293.15, None, '')),
  'Original table does not resolve salinity for this record. It is not arbitrary brine or ocean '
  'thermodynamics.'),
 ('solid.ice',
  'Ice at 0 C',
  'ice',
  'grain',
  (),
  (('density', 917.0, 'kg/m3', 'WATER2024', 'Table 6: ice at 0 C', None, 'reported', 273.15, None, ''),
   ('conductivity', 2.2, 'W/m/K', 'WATER2024', 'Table 6: ice at 0 C', None, 'reported', 273.15, None, ''),
   ('heat_capacity', 2040.0, 'J/kg/K', 'WATER2024', 'Table 6: ice at 0 C', None, 'reported', 273.15, None, '')),
  'Fixed ice reference only; no freezing latent heat, temperature law or automatically inferred fluid phase.'))

SEDIMENT_RECIPES = (('quartz_sand_or_silt_matrix',
  (('mineral.quartz', 1.0),),
  'Quartz-only grain endmember; sand/silt particle size belongs to the layer, not mineral density. No '
  'implicit pore fraction.'),
 ('feldspathic_sand_matrix',
  (('mineral.quartz', 0.6), ('mineral.albite', 0.25), ('mineral.orthoclase', 0.15)),
  'Declared illustrative grain-volume recipe, not a measured universal arkose.'),
 ('illitic_mud_matrix',
  (('mineral.illite', 0.7), ('mineral.quartz', 0.3)),
  'Declared illite-rich example; not every clay or mud.'),
 ('smectitic_mud_matrix',
  (('mineral.smectite', 0.7), ('mineral.quartz', 0.3)),
  'Declared smectite-rich example; no swelling/hydration law.'),
 ('calcareous_ooze_matrix',
  (('mineral.calcite', 1.0),),
  'Calcite grain endmember; porosity and fluid must be supplied separately.'),
 ('mixed_carbonate_matrix',
  (('mineral.calcite', 0.8), ('mineral.quartz', 0.2)),
  'Declared mixed grain-volume example, not a universal marl.'),
 ('felsic_regolith_matrix',
  (('mineral.quartz', 0.3), ('mineral.albite', 0.3), ('mineral.orthoclase', 0.3), ('mineral.illite', 0.1)),
  'Illustrative mineral recipe only; no automatic weathering or prescribed soil pore content.'))
